### ISSUE TITLE
vendure-plugin-invoices needs `body-parser`

### ISSUE THREAD

**Issue by casabian** [Pinelab-studio/pinelab-vendure-plugins#13]
Same as for #1 vendure-plugin-invoices requires `json` body parser for route `/invoices/preview`.

I currently fixed it by adding json as middleware in the vendure `apiOptions`

```typescript
import { ApiOptions } from "@vendure/core";
import { json } from "body-parser";
export const apiOptions: ApiOptions = {
  /* .... */
  middleware: [
    {
      route: "/invoices/preview",
      handler: json({ limit: "5mb" }),
    },
  ],
};
```

**Comment by martijnvdbrug** [comment]
@casabian  Can you supply some more information about what error you are getting and how to reproduce?

I cannot seem to reproduce the issue...

**Comment by casabian** [comment]
Need to revert to an older revision to give you the correct error message but it was related to data.template being null when using the `/invoices/preview` endpoint.

**Comment by casabian** [comment]
As I promised the error message without a json body-parser defined for the route `/invoice/preview`

```
error [Vendure Server] No template given
Error: No template given
    at InvoiceController.preview (node_modules/vendure-plugin-invoices/dist/api/invoice.controller.js:40:19)
    at node_modules/@nestjs/core/router/router-execution-context.js:38:29  
```

**Comment by martijnvdbrug** [comment]
@casabian Closing this because of inactivity. Feel free to re-open if you are still running into issues with the invoices plugin.
