### ISSUE TITLE
Getting issue with vendure-plugin-stock-monitoring with postgresql database

### ISSUE THREAD

**Issue by ashishkpaul** [Pinelab-studio/pinelab-vendure-plugins#512]
**Which plugin/repository is the issue about?**
vendure-plugin-stock-monitoring

**Describe the bug**
With a same setup i tried both database postgresql and mariadb but when i am using 'stock monitoring' plugin with postgresql version 16 getting

 ```
[server] error 10/2/24, 1:06 PM - [Vendure Server] column "stockonhand" does not exist[server] QueryFailedError: column "stockonhand" does not exist
[server]     at PostgresQueryRunner.query (/home/ubuntu/projects/vendure/core/buylits-ecom/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:331:19)
[server]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[server]     at async SelectQueryBuilder.loadRawResults (/home/ubuntu/projects/vendure/core/buylits-ecom/node_modules/src/query-builder/SelectQueryBuilder.ts:3805:25)
[server]     at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/ubuntu/projects/vendure/core/buylits-ecom/node_modules/src/query-builder/SelectQueryBuilder.ts:3551:26)
[server]     at async SelectQueryBuilder.getRawAndEntities (/home/ubuntu/projects/vendure/core/buylits-ecom/node_modules/src/query-builder/SelectQueryBuilder.ts:1670:29)
[server]     at async SelectQueryBuilder.getMany (/home/ubuntu/projects/vendure/core/buylits-ecom/node_modules/src/query-builder/SelectQueryBuilder.ts:1760:25) 
``` 
but no issue with mariadb. and there is no pending migration

```
npx vendure migrate


┌  🛠️️ Vendure migrations
│
◇  What would you like to do?
│  Generate a new migration
│
◇  Project analyzed
│
●  Using VendureConfig from src/vendure-config.ts
│
◇  Enter a meaningful name for the migration
│  stock-monitoring
Using postgres connection
│
◇  Migration file location
│  /home/ubuntu/projects/vendure/core/buylits-ecom/src/migrations
│
verbose 10/2/24, 1:12 PM - [HardenPlugin] Configuring HideValidationErrorsPlugin 
◇  No changes in database schema were found, so no migration was generated
│
└  ✅ Done!
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- NodeJS version: v20.15.1
- Vendure version: v3.0.3 
- Plugin version 1.4.1
- Database : postgresql
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment]
Sorry, I see I haven't replied yet. This is still on my radar, but haven't been able to reproduce it yet.

**Comment by brmk** [comment]
I was able to reproduce this on PostgreSQL. The issue happens because of how the alias is defined in the query:

```
.addSelect('SUM(stockLevel.stockOnHand) as stockOnHand')
```

This creates a SQL alias, but TypeORM doesn’t register it internally. So when `stockOnHand` is later referenced in `.andWhere()` or `.orderBy()`, it just passes that string directly into the SQL — without quoting it.

This works in MySQL/MariaDB because they're case-insensitive by default for column names. But PostgreSQL is case-sensitive, and it interprets stockOnHand as stockonhand unless explicitly quoted — which leads to:

```
column "stockonhand" does not exist
```

-------

There are two fixes that would work (both of them are a bit ugly):

1. Write `stockOnHand` and `stockAllocated` aliases in snake_case.
2. Enclose these variables in quotes, so that Postgres correctly handles camelCase alias (`stockOnHand` -> `"stockOnHand"`)

@martijnvdbrug what are you thoughts?


Here is the patch that works for me at the moment

```
diff --git a/node_modules/@pinelab/vendure-plugin-stock-monitoring/dist/api/stock-monitoring.resolver.js b/node_modules/@pinelab/vendure-plugin-stock-monitoring/dist/api/stock-monitoring.resolver.js
index c0f1059..090ad94 100644
--- a/node_modules/@pinelab/vendure-plugin-stock-monitoring/dist/api/stock-monitoring.resolver.js
+++ b/node_modules/@pinelab/vendure-plugin-stock-monitoring/dist/api/stock-monitoring.resolver.js
@@ -27,17 +27,17 @@ let StockMonitoringResolver = class StockMonitoringResolver {
             .leftJoin('variant.product', 'product')
             .leftJoin('variant.stockLevels', 'stockLevel')
             .addGroupBy('variant.id')
-            .addSelect(['SUM(stockLevel.stockOnHand) as stockOnHand'])
-            .addSelect(['SUM(stockLevel.stockAllocated) as stockAllocated'])
+            .addSelect('SUM(stockLevel.stockOnHand)', 'stockOnHand')
+            .addSelect('SUM(stockLevel.stockAllocated)', 'stockAllocated')
             .leftJoin('product.channels', 'channel')
             .where('variant.enabled = true')
-            .andWhere('stockOnHand - stockAllocated < :threshold', {
+            .andWhere('"stockOnHand" - "stockAllocated" < :threshold', {
             threshold: stock_monitoring_plugin_1.StockMonitoringPlugin.threshold,
         })
             .andWhere('variant.deletedAt IS NULL')
             .andWhere('channel.id = :channelId', { channelId: ctx.channelId })
             .limit(100)
-            .orderBy('stockOnHand', 'ASC')
+            .orderBy('"stockOnHand"', 'ASC')
             .getMany();
     }
 };
```

**Comment by martijnvdbrug** [comment]
@brmk thanks for your help on this! I will take a look tomorrow: maybe there is a way to avoid this entirely.

**Comment by martijnvdbrug** [comment]
@brmk I've applied your patch to the code, thanks for the help. I don't think there is anything wrong with your approach. It is  published as [v1.5.0 ](https://plugins.pinelab.studio/plugin/vendure-plugin-stock-monitoring/)
